# Generated by Django 3.0 on 2020-04-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='DNI')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('movil', models.CharField(max_length=13, verbose_name='Móvil')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.CharField(max_length=12, verbose_name='Número de orden')),
                ('operador', models.CharField(blank=True, max_length=20, null=True, verbose_name='Operador')),
                ('instalacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Instalación')),
                ('cliente', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cliente')),
                ('destino', models.CharField(blank=True, max_length=50, null=True, verbose_name='Destino')),
                ('direccion', models.CharField(blank=True, max_length=80, null=True, verbose_name='Dirección')),
                ('tfno', models.IntegerField(blank=True, default=0, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Conductor')),
            ],
        ),
    ]
