# Generated by Django 3.0 on 2020-04-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20200403_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='driver',
            field=models.IntegerField(choices=[(1, 'ALEJANDRO PÉREZ'), (2, 'ISABEL GÓMEZ'), (3, 'JUAN MÉNDEZ'), (4, 'PABLO GARCÍA ')], default=1, verbose_name='Conductor'),
        ),
    ]
