# Generated by Django 3.0 on 2020-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo de Vehículo')),
                ('matricula', models.CharField(max_length=8, verbose_name='Matrícula')),
                ('fechaadr', models.DateTimeField(auto_now=True, verbose_name='Fecha ADR')),
                ('fechaitv', models.DateTimeField(auto_now=True, verbose_name='Fecha ITV')),
                ('fechaarnes', models.DateTimeField(auto_now=True, verbose_name='Fecha Arnés')),
                ('fechatablas', models.DateTimeField(auto_now=True, verbose_name='Fecha Tablas Calibración')),
                ('editado', models.DateTimeField(auto_now=True, verbose_name='Editado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['matricula', 'editado'],
            },
        ),
    ]
