# Generated by Django 3.0 on 2020-02-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='compartimentos',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Compartimentos'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='contador',
            field=models.BooleanField(blank=True, null=True, verbose_name='Contador'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ejes',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Ejes'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaadr',
            field=models.DateTimeField(verbose_name='Fecha ADR'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaarnes',
            field=models.DateTimeField(verbose_name='Fecha Arnés'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaitv',
            field=models.DateTimeField(verbose_name='Fecha ITV'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechatablas',
            field=models.DateTimeField(verbose_name='Fecha Tablas Calibración'),
        ),
    ]
