# Generated by Django 3.0 on 2020-02-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20200224_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='compartimentos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Compartimentos'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='ejes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ejes'),
        ),
    ]
