# Generated by Django 3.0 on 2020-02-24 10:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_auto_20200224_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
