# Generated by Django 3.0 on 2020-02-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_vehiculo_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
