# Generated by Django 3.0 on 2020-03-01 01:51

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_vehiculo_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fechaarnes',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carga_pesados',
            field=models.BooleanField(default=False, verbose_name='Carga Pesados'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='carga_queroseno',
            field=models.BooleanField(default=False, verbose_name='Carga Queroseno'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='equipo_adicional',
            field=models.BooleanField(default=False, verbose_name='Equipo Adicional'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='equipos',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Indicar equipos adicionales'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechatarjetatte',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Tarjeta Tte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='no_petroliferos',
            field=models.BooleanField(default=False, verbose_name='No Petrolíferos'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='peso_maximo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peso Máximo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='solo_gasoleos',
            field=models.BooleanField(default=False, verbose_name='Sólo Gasóleos'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tara',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tara'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_adr',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo ADR'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Tractora'), (2, 'Semirremolque'), (3, 'Rigido'), (4, 'Cisterna')], default=1, verbose_name='Tipo de Vehículo'),
        ),
    ]
