# Generated by Django 2.1 on 2020-03-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_auto_20200323_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaadr',
            field=models.DateTimeField(verbose_name='Fecha ADR'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechaitv',
            field=models.DateTimeField(verbose_name='Fecha ITV'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechatablas',
            field=models.DateTimeField(verbose_name='Fecha Tablas Calibración'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='fechatarjetatte',
            field=models.DateTimeField(verbose_name='Fecha Tarjeta Tte'),
        ),
    ]
