# Generated by Django 3.0.3 on 2020-03-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehiculos', '0010_auto_20200323_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='compartimentos',
            new_name='compart',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='creado_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='fechaseguro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha vencimiento seguro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nacion',
            field=models.IntegerField(choices=[(1, 'Andorra'), (2, 'España'), (3, 'Francia'), (4, 'Portugal'), (5, 'UK')], default=2, verbose_name='Nación'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='contador',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Contador'),
        ),
        migrations.CreateModel(
            name='Compartimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartimento', models.IntegerField(blank=True, null=True, verbose_name='Comparimento')),
                ('capacidad', models.IntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('altura', models.IntegerField(blank=True, null=True, verbose_name='Altura')),
                ('tag', models.CharField(blank=True, max_length=10, null=True, verbose_name='TAG')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo')),
            ],
            options={
                'verbose_name': 'compartimento',
                'verbose_name_plural': 'compartimentos',
                'ordering': ['compartimento'],
            },
        ),
    ]
