# Generated by Django 3.0.3 on 2020-03-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_auto_20200325_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compartimentos',
            old_name='camion',
            new_name='vehiculo',
        ),
    ]
