# Generated by Django 3.0 on 2020-04-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0013_remove_compartimentos_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartimentos',
            name='camion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vehiculos.Vehiculo'),
        ),
    ]
