# Generated by Django 3.0.5 on 2020-04-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0014_compartimentos_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartimentos',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/%Y/%m/%d'),
        ),
        migrations.AlterIndexTogether(
            name='vehiculo',
            index_together={('id', 'slug')},
        ),
    ]
